services:
  - type: web
    name: early-adopter-agent
    env: node
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: early-adopter-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://early-adopter-agent.onrender.com/api/auth/google/callback
      - key: GOOGLE_USER_EMAIL
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: debug
      - key: ANALYTICS_ENABLED
        value: "true"
      - key: ANALYTICS_SAMPLE_RATE
        value: "100"
      - key: FEEDBACK_COLLECTION_INTERVAL
        value: "7"
      - key: APP_URL
        value: https://early-adopter-agent.onrender.com
      - key: CLIENT_URL
        value: https://early-adopter-agent.onrender.com

databases:
  - name: early-adopter-db
    databaseName: early_adopter_agent
    user: early_adopter_user
    plan: free
    ipAllowList: [] 